version: '1.0'
stages:
  - clone
  - test
steps:
  main_clone:
    title: Clone repository
    stage: clone
    type: git-clone
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_SHORT_REVISION}}
    git: github
  setup_github_token:
    title: Setup GitHub token
    stage: clone
    image: codefresh/cli
    commands:
      - echo GITHUB_TOKEN=$(codefresh get context github --decrypt -o yaml | yq -r .spec.data.auth.password) >> ${{CF_VOLUME_PATH}}/env_vars_to_export
  tests_php74:
    stage: test
    title: Run PHP tests 7.4
    image: gcr.io/linio-support/docker-php:7.4
    commands:
      - composer config -g github-oauth.github.com ${GITHUB_TOKEN}
      - composer install --no-scripts -o --no-interaction --no-suggest
      - composer test
  tests_php71:
    title: Run PHP tests 7.1
    stage: test
    image: gcr.io/linio-support/docker-php:7.1
    commands:
      - composer config -g github-oauth.github.com ${GITHUB_TOKEN}
      - composer install --no-scripts -o --no-interaction --no-suggest
      - composer test
