version: '3.7'
services:
  php-cs-fixer:
    image: linio/seller-center-sdk:latest
    init: true
    volumes:
      - .:/application
    entrypoint: vendor/bin/php-cs-fixer
    command: fix --verbose --show-progress=estimating

  composer:
    image: linio/seller-center-sdk:latest
    init: true
    volumes:
      - .:/application
    entrypoint: composer

  phpunit:
    image: linio/seller-center-sdk:latest
    init: true
    volumes:
      - .:/application
    entrypoint: vendor/bin/phpunit

  php:
    image: linio/seller-center-sdk:latest
    init: true
    volumes:
      - .:/application
    environment:
      LINIO_ENV: local
